const GREETINGS_GAME = [
    {
        gameObject: [
        {
          id: 1,
          element_one: "Hello / Hi",
          element_two: "Ciao",
        },
        {
          id: 2,
          element_one: "Good morning",
          element_two: "Buon giorno",
        },
        {
          id: 3,
          element_one: "Good evening",
          element_two: "Buona sera",
        },
        {
          id: 4,
          element_one: "Good night",
          element_two: "Buona notte",
        },
        {
          id: 5,
          element_one: "Hi (formal)",
          element_two: "Salve",
        },
        {
          id: 6,
          element_one: "Good afternoon",
          element_two: "Buon pomeriggio",
        },
        {
          id: 7,
          element_one: "How are you?",
          element_two: "Come stai?",
        },
        {
          id: 8,
          element_one: "My name is Giulia",
          element_two: "Mi chiamo Giulia",
        },
        {
          id: 9,
          element_one: "Nice to meet you",
          element_two: "Piacere di conoscerti",
        },
        {
          id: 10,
          element_one: "What's your name?",
          element_two: "Come ti chiami?",
        },
        {
          id: 11,
          element_one: "My name is Roberto",
          element_two: "Mi chiamo Roberto",
        },
      ],
    },
  ];
  
  export default GREETINGS_GAME;
  