const NUMBERS_LESSSON = [
  {
    Lesson_title: "Numbers and Counting",
    lessonUrl: "/italian-grammar/a1/lesson/numbers",
    gameUrl: "/italian-grammar/a1/game/numbers",
    content: `
    <p> Cardinal numbers are the basic numbers we use to count things and express quantities. They are important in our everyday language, like saying \"one apple\" or \"two books,\" and in math when we do addition, subtraction, and other calculations. In simple terms, they're the numbers we use when we want to talk about how many of something there are. </p>
    </br>
      <h3>Counting from 1 to 100</h3>
      <p> In Italian, counting is quite straightforward. Lets start from 1 to 100 :</p>
      <table border="1">
      <tr>
          <th>Number</th>
          <th>Italian</th>
          <th>Pronunciation</th>
      </tr>
      <tr>
          <td>1</td>
          <td>Uno</td>
          <td>OO-noh</td>
      </tr>
      <tr>
          <td>2</td>
          <td>Due</td>
          <td>DOO-eh</td>
      </tr>
      <tr>
          <td>3</td>
          <td>Tre</td>
          <td>TREH</td>
      </tr>
      <tr>
          <td>4</td>
          <td>Quattro</td>
          <td>KWAT-tro</td>
      </tr>
      <tr>
          <td>5</td>
          <td>Cinque</td>
          <td>CHEEN-kweh</td>
      </tr>
      <tr>
          <td>6</td>
          <td>Sei</td>
          <td>SAY</td>
      </tr>
      <tr>
          <td>7</td>
          <td>Sette</td>
          <td>SET-teh</td>
      </tr>
      <tr>
          <td>8</td>
          <td>Otto</td>
          <td>OH-toh</td>
      </tr>
      <tr>
          <td>9</td>
          <td>Nove</td>
          <td>NOH-veh</td>
      </tr>
      <tr>
          <td>10</td>
          <td>Dieci</td>
          <td>DYEH-chee</td>
      </tr>
      <tr>
          <td>11</td>
          <td>Undici</td>
          <td>OON-dee-chee</td>
      </tr>
      <tr>
          <td>12</td>
          <td>Dodici</td>
          <td>DOH-dee-chee</td>
      </tr>
      <tr>
          <td>13</td>
          <td>Tredici</td>
          <td>TREH-dee-chee</td>
      </tr>
      <tr>
          <td>14</td>
          <td>Quattordici</td>
          <td>KWAH-tor-dee-chee</td>
      </tr>
      <tr>
          <td>15</td>
          <td>Quindici</td>
          <td>KWEEN-dee-chee</td>
      </tr>
      <tr>
          <td>16</td>
          <td>Sedici</td>
          <td>SEH-dee-chee</td>
      </tr>
      <tr>
          <td>17</td>
          <td>Diciassette</td>
          <td>dee-CHAHS-set-teh</td>
      </tr>
      <tr>
          <td>18</td>
          <td>Diciotto</td>
          <td>dee-CHOH-toh</td>
      </tr>
      <tr>
          <td>19</td>
          <td>Diciannove</td>
          <td>dee-CHAHN-noh-veh</td>
      </tr>
      <tr>
          <td>20</td>
          <td>Venti</td>
          <td>VEN-tee</td>
      </tr>
  </table>

      </br>
      <h3>Counting from 20 to 100</h3>
    <p>Now, let's move on to counting from 20 to 100 in Italian. You already know the numbers up to 20, so this will be an extension of what you've learned.</p>
    <table border="1">
    <tr>
        <th>Number</th>
        <th>Italian</th>
        <th>Pronunciation</th>
    </tr>
    <tr>
        <td>21</td>
        <td>Ventiuno</td>
        <td>VEN-tee-OO-noh</td>
    </tr>
    <tr>
        <td>22</td>
        <td>Ventidue</td>
        <td>VEN-tee-DOO-eh</td>
    </tr>
    <tr>
        <td>23</td>
        <td>Ventitré</td>
        <td>VEN-tee-TREH</td>
    </tr>
    <tr>
        <td>30</td>
        <td>Trenta</td>
        <td>TREN-tah</td>
    </tr>
    <tr>
      <td>34</td>
       <td>Trentaquattro</td>
    <td>TREN-tah-KWAT-tro</td>
  </tr>
  <tr>
    <td>35</td>
    <td>Trentacinque</td>
    <td>TREN-tah-CHEEN-kweh</td>
  </tr>
    <tr>
        <td>40</td>
        <td>Quaranta</td>
        <td>KWAH-rahn-tah</td>
    </tr>
    <tr>
    <td>46</td>
    <td>Quarantasei</td>
    <td>KWAH-rahn-ta-SAY</td>
</tr>
<tr>
    <td>47</td>
    <td>Quarantasette</td>
    <td>KWAH-rahn-ta-SET-teh</td>
</tr>
    <tr>
        <td>50</td>
        <td>Cinquanta</td>
        <td>CHEEN-KWAHN-tah</td>
    </tr>
    <tr>
    <td>58</td>
    <td>Cinquantotto</td>
    <td>CHEEN-KWAHN-toh-toh</td>
</tr>
<tr>
    <td>59</td>
    <td>Cinquantanove</td>
    <td>CHEEN-KWAHN-tah-noh-veh</td>
</tr>

    <tr>
        <td>60</td>
        <td>Sessanta</td>
        <td>SEHSS-AHN-tah</td>
    </tr>
    <tr>
    <td>61</td>
    <td>Sessantuno</td>
    <td>SEHSS-AHN-too-noh</td>
</tr>
<tr>
    <td>62</td>
    <td>Sessantadue</td>
    <td>SEHSS-AHN-tah-DOO-eh</td>
</tr>
    <tr>
        <td>70</td>
        <td>Settanta</td>
        <td>SET-TAHN-tah</td>
    </tr>
    <tr>
    <td>73</td>
    <td>Settantatre</td>
    <td>SET-tahn-TAH-treh</td>
</tr>
<tr>
    <td>74</td>
    <td>Settantadue</td>
    <td>SET-tahn-tah-DOO-eh</td>
</tr>
    <tr>
        <td>80</td>
        <td>Ottanta</td>
        <td>OHT-TAHN-tah</td>
    </tr>
    <tr>
    <td>85</td>
    <td>Ottantacinque</td>
    <td>OHT-TAHN-tah-CHEEN-kweh</td>
</tr>
<tr>
    <td>86</td>
    <td>Ottantasei</td>
    <td>OHT-TAHN-tah-SAY</td>
</tr>

    <tr>
        <td>90</td>
        <td>Novanta</td>
        <td>NOH-VAHN-tah</td>
    </tr>
    <tr>
    <td>97</td>
    <td>Novantasette</td>
    <td>NOH-vahn-tah-SET-teh</td>
</tr>
<tr>
    <td>98</td>
    <td>Novantotto</td>
    <td>NOH-vahn-toh-toh</td>
</tr>
<tr>
    <td>99</td>
    <td>Novantanove</td>
    <td>NOH-vahn-tah-noh-veh</td>
</tr>

    <tr>
        <td>100</td>
        <td>Cento</td>
        <td>CHEN-toh</td>
    </tr>
    </table>
    <p>Remember that counting in Italian is often a combination of the tens and the ones. For example, "trentuno" is 31, "quarantadue" is 42, and "cinquantasette" is 57. Continue this pattern up to 100, and you'll have a good foundation for counting in Italian.</p>
 

    </br>
    <h3>Counting from 100 to 1000</h3>
  <p>Certainly! Counting from 100 to 1000 in Italian involves understanding the pattern for combining the hundreds and tens along with the units. Here's how you can count in that range:</p>
 
  <table border="1">
  <tr>
      <th>Number</th>
      <th>Italian</th>
      <th>Pronunciation</th>
  </tr>
    <tr>
    <td>100</td>
    <td>Cento</td>
    <td>CHEN-toh</td>
</tr>
<tr>
    <td>101</td>
    <td>Centouno</td>
    <td>CHEN-toh-OO-noh</td>
</tr>
<tr>
    <td>111</td>
    <td>Centoundici</td>
    <td>CHEN-toh-OON-dee-chee</td>
</tr>
<tr>
    <td>200</td>
    <td>Duecento</td>
    <td>DOO-eh-CHEN-toh</td>
</tr>
<tr>
    <td>202</td>
    <td>Duecentodue</td>
    <td>DOO-eh-CHEN-toh-DOO-eh</td>
</tr>
<tr>
    <td>222</td>
    <td>Duecentoventidue</td>
    <td>DOO-eh-CHEN-toh-ven-tee-DOO-eh</td>
</tr>
<tr>
    <td>3034</td>
    <td>Trecentotrentaquattro</td>
    <td>TREH-chen-toh-tren-tah-KWAT-tro</td>
</tr>
<tr>
    <td>356</td>
    <td>Trecentocinquantasei</td>
    <td>TREH-chen-toh-CHEEN-kwahn-ta-SAY</td>
</tr>
<tr>
    <td>430</td>
    <td>Quattrocentotrenta</td>
    <td>KWAT-tro-CHEN-toh-TREN-tah</td>
</tr>
<tr>
    <td>499</td>
    <td>Quattrocentonovantanove</td>
    <td>KWAT-tro-CHEN-toh-NOH-vahn-tah-NOH-veh</td>
</tr>
<tr>
    <td>511</td>
    <td>Cinquecentoundici</td>
    <td>CHEEN-kweh-CHEN-toh-OON-dee-chee</td>
</tr>
<tr>
    <td>594</td>
    <td>Cinquecentonovantaquattro</td>
    <td>CHEEN-kweh-CHEN-toh-NOH-vahn-tah-KWAT-tro</td>
</tr>
<tr>
    <td>649</td>
    <td>Seicentoquarantanove</td>
    <td>SAY-chen-toh-KWAH-rahn-tah-NOH-veh</td>
</tr>
<tr>
    <td>611</td>
    <td>Seicentoundici</td>
    <td>SAY-chen-toh-OON-dee-chee</td>
</tr>
<tr>
    <td>734</td>
    <td>Settecentotrentaquattro</td>
    <td>SET-teh-CHEN-toh-TREN-tah-KWAT-tro</td>
</tr>
<tr>
    <td>790</td>
    <td>Settecentonovanta</td>
    <td>SET-teh-CHEN-toh-NOH-vahn-tah</td>
</tr>
<tr>
    <td>811</td>
    <td>Ottocentoundici</td>
    <td>OHT-toh-CHEN-toh-OON-dee-chee</td>
</tr>
<tr>
    <td>888</td>
    <td>Ottocentottantotto</td>
    <td>OHT-toh-CHEN-toh-tahn-toh-toh</td>
</tr>
<tr>
    <td>919</td>
    <td>Novecentodiciannove</td>
    <td>NOH-veh-CHEN-toh-dee-CHAHN-noh-veh</td>
</tr>
<tr>
    <td>999</td>
    <td>Novecentonovantanove</td>
    <td>NOH-veh-CHEN-toh-NOH-vahn-tah-NOH-veh</td>
</tr>
<tr>
    <td>1000</td>
    <td>Mille</td>
    <td>MEE-leh</td>
</tr>
</table>
<p>To continue counting beyond 1000, you can use the same pattern by combining the hundreds and tens with the units, just like in the examples provided earlier. For example, "1001" is "Milleuno" (MEE-leh-OO-noh), where "Mille" means a thousand, and "uno" means one.</p>
  `,
  },
  // Add more lesson objects as needed
];

export default NUMBERS_LESSSON;
